---
framework: mocha
postmerge:
  pattern:
    - "test/scripts/box/box.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
premerge:
  - "test/scripts/box/box.js"
prerun:
  - npm i
  - export NODE_ENV='test'
  - export NO_DEPRECATION='body-parser,express'
postrun:
  - node --version
  - echo "Ba Dum TAS... -_-"
stability:
  consecutive_runs: 5
version: 2.0
